### PR TITLE
Add QoS overriding options

### PR DESCRIPTION
**Pull request by Bitterisland6**
I had a problem when using `imu_complementary_filter` node - provided topics for subscription had incompatible reliabilities. Therefore I've added possibility of overriding QoS settings (history, depth, durability and reliability) for the subscribers in the node.
I have created a config file with required parameters (check [this](https://docs.ros.org/en/rolling/p/rclcpp/generated/classrclcpp_1_1QosOverridingOptions.html) tutorial) and included all node's parameters in it.

### CODE REVIEW

**Comment by mintar** [comment]
This looks very useful, thanks!

Could you have a look at the CI errors? I just had a quick glance. 

* The GitHub CI is complaining about the formatting of your yaml file (trailing whitespace, missing end-of-file). You should be able to fix this semi-automatically by installing pre-commit locally, see README: https://github.com/CCNYRoboticsLab/imu_tools/tree/rolling?tab=readme-ov-file#pre-commit-formatting-checks
* The ROS buildfarm errors seem to be caused by obsolete headers, see details. I believe only 7 of those warnings are from your code and 4 already existed (sorry!).

**Comment by Bitterisland6** [comment]
@mintar  I've checked the ROS buildfarm errors and most of them are regarding the obsolete headers. In my code I didn't need to add any headers, therefore the only errors connected to this PR are the ones regarding the use of `rmw_qos_profile_default` - I have fixed those in the last commit.

The problem with other CI checks failing is that the constructor for `Subscriber` class from message_filters has switched from the use of `rmw_qos_profile_t` to `rclcpp::QoS`. Therefore I can't make it work for all the package versions at the same time. 

I wanted to make a separate PR with fixes to the buildfarm errors caused not by my code, but there would be the same problem - the fixes would work only for the `rolling` part of workflows.

In such situation what should I do?

**Comment by mintar** [comment]
Thanks for all the work so far!

So, looking at the CI results:

* Commit b085b0e passes the GitHub CI tests for Humble, Iron, and Rolling, plus the ROS Buildfarm test for Jazzy. Fails the ROS Buildfarm test for Rolling with 11 warnings.

* Commit 7fe1822 + 789b917 breaks compilation for Humble, Iron and Jazzy, but fixes two warnings on Rolling, so there are only 9 left.

I would suggest the following:

* Drop commits 7fe1822 + 789b917

* Squash all your commits up until b085b0e into one, then force-push

* Tell me when you're done and I will merge your pull request into the `rolling` branch. I will then also manually merge it into the `humble`, `iron` and `jazzy` branches. (BTW, I have just added a `jazzy` branch just for this purpose). I'll also do releases into humble, iron, jazzy and rolling.

Now, all tests should be working again except for the 11 deprecation warnings in Rolling.

Afterwards, we'll have to see how to continue. One way forward would be that we split the `rolling` branch from the rest and don't run any tests except the `rolling` tests in that branch. Then you submit additional PRs (for example including 7fe1822 + 789b917 again) without having to worry about breaking the other branches. The only disadvantage is that we will have to back-port any future PRs.

What do you think?

**Comment by Bitterisland6** [comment]
@mintar I have applied the suggested changes (dropped and squashed commits).
Regarding next step, I don't see any other way than splitting rolling branch from the other branches - You cannot fix the "deprecated includes" warning from rolling without creating errors for humble etc. (the newer header files don't exist for those ROS versions). What's more, usage of `rmw_qos_profile_t` is marked as deprecated for all the methods and constructors in rolling version of `message_filters` package, but the older ROS versions don't have functionality to use `rclcpp::QoS`.

Therefore making rolling a separate branch is the only option to have this QoS overriding options working, and all CI checks passing successfully (I agree that the need of back-port every new functionality is a disadvantage).

**Comment by mintar** [comment]
Thanks! I've also finished all the housekeeping chores:

* [x] PR merged into `rolling`
* [x] merged into `humble`, `iron`, `jazzy`
* split the branches:
  - [x] removed `rolling` from the `humble`/`iron`/`jazzy` CI (#209)
  - [x] removed `humble`/`iron`/`jazzy` from the `rolling` CI (#210)
* released 2.1.5 into...
  - [x] `humble` (ros/rosdistro#43007)
  - [x] `iron` (ros/rosdistro#43019)
  - [x] `jazzy` (ros/rosdistro#43020)
* released 2.2.0 into...
  - [x] `rolling` (ros/rosdistro#43010)

From now on, the 2.2.* releases will go to `rolling` and the 2.1.* releases to the other branches. 

This means you're free to open PRs to `rolling` without affecting the other branches, and CI will also only run for `rolling`.

**Comment by mintar** [comment]
By the way, I've noticed that the `imu_filter_madgwick` uses `rmw_qos_profile_sensor_data`. Would that have worked for the complementary filter instead of what you did in this PR? I don't really use ROS2 yet, so I don't know.

**Comment by Bitterisland6** [comment]
@mintar sorry for late response. In my case using the policy from `imu_filter_madgwick` would work, as `sensor_data` QoS profile has the same policy as my topics. But this wouldn't be the solution in general case. I know that there are possibilities for publisher-subscriber communication with different QoS, but I think having the possibility to configure the  policy is better. Also this solution would still cause the CI errors, as every use of `rmw_qos_profile_t` is deprecated for ROS `rolling` version.

**Pull request merged**
