### PR TITLE
Groovy port of rviz_imu_plugin

### PR DESCRIPTION
**Pull request by lorenzoriano**
This works under groovy and solves issue#9

### CODE REVIEW

**Comment by mintar** [comment]
Hi @lorenzoriano, somehow my commits slipped into your pull request; especially 44b878120333745e6d62e2ae9f9dbf1351ecdafa shouldn't be merged into master just yet (there's a bug, but this commit only fixes a special case).

I suggest merging 33f4b6873160e2b6c409b353c79a5fbe40b43896 and 123e8cc179ffd46b9b0fef1eb13a77b028ac633c into a new branch named `groovy`, since they will break fuerte compatibility. Just my 2 cents. :-)

**Comment by lorenzoriano** [comment]
Thanks @mintar , I've removed your commit and creating a new pull request to change the branch.

**Comment by lorenzoriano** [comment]
This repository has no branch named groovy, can someone please create one so I can add my pull request? (or tell me if I can issue a pull request on a new branch?)

**Comment by mintar** [comment]
You can't issue a pull request on a new branch, @idryanov has to create one first.

**Comment by lorenzoriano** [comment]
Ok, thanks. Is this repository still active anyway?

**Comment by idryanov** [comment]
Hi guys,

Thank you for the tickets and sorry I haven't been able to reply earlier. I
gave you both access to the repo, feel free to commit and merge as you see
fit!

On Wed, Jun 26, 2013 at 10:20 AM, Lorenzo Riano notifications@github.comwrote:

> Ok, thanks. Is this repository still active anyway?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ccny-ros-pkg/imu_tools/pull/12#issuecomment-20064714
> .

## 

Ivan Dryanovski
The Graduate Center, City University of New York (CUNY)
CCNY Robotics Lab
http://robotics.ccny.cuny.edu/People/Dryanovski

**Comment by mintar** [comment]
Thanks for your trust, @idryanov! :-)

I've created a new branch "groovy" and merged this pull request.

**Comment by georgebrindeiro-vtex** [comment]
@lorenzoriano I am having a similar problem with [rviz_plugin_covariance](https://github.com/laas/rviz_plugin_covariance), where can I find more info on the changes made to rviz plugins? The only reference I have is this [tutorial](http://docs.ros.org/hydro/api/rviz_plugin_tutorials/html/display_plugin_tutorial.html), but it assumes I am starting from scratch. If you have any tips on how to move faster, let me know!

**Comment by mintar** [comment]
@georgebrindeiro Since your question doesn't have anything to do with this issue, it would be better if you contacted @lorenzoriano directly instead of commenting here. Thanks! :-)

**Comment by georgebrindeiro-vtex** [comment]
Alright, thanks for the feedback and sorry about that!

**Pull request closed without merging**
