### PR TITLE
added parameter: publish_tf

### PR DESCRIPTION
**Pull request by mintar**
When the imu is used together with other packages, such as
robot_pose_ekf, publishing the transform often interferes with those
packages. This parameter allows to disable tf publishing.

### CODE REVIEW

**Comment by idryanov** [comment]
Hi Martin, thank you for the pull request. I will merge the changes, although I'm not sold on the "upside down" fix. Wouldn't is be better to handle this by a ROS static tf which links the imu frame to a an upright imu frame?

**Comment by mintar** [comment]
Hi Ivan, I'm still figuring out how pull requests work -- I didn't mean to request that you merge the "upside down" fix, it's more of a workaround and should be cleaned up before merging into your branch. I've pushed that commit after submitting the pull request.

The trouble is that a static tf (which is what we're using) doesn't work: After initialization, the robot starts out pointing upside down, then gradually rotates upward over the next few seconds. Try for yourself with the rosbag I just committed.

**Comment by mintar** [comment]
FYI, the transform I use to link `/base_link` (x forward, z up) to `/imu` is:

```
<node pkg="tf" type="static_transform_publisher" name="$(anon static_transform_publisher)"
  args="0 0 0 0 1 0 0 /base_link /imu 10" />
```

**Comment by idryanov** [comment]
I see. Ok ill remove that before i merge.

**Comment by mintar** [comment]
All right, I removed the offending commit (44b878120333745e6d62e2ae9f9dbf1351ecdafa) and merged the other two.

**Pull request merged**
