### PR TITLE
replace invSqrt() with 1/sqrt()

### LINKED ISSUE #17: Estimate diverges under constant input
I noticed that it drifted a lot with my IMU so I did a simple test.

I supplied (0,0,0) for angular velocity, (0, 0, 9.81) for linear acceleration and (-0.420,+0.302, 0.835) for magnetic vector. The resulting orientation (I looked at Euler angles) was very noisy and didn't converge (picture below). 
original_code

If, however, the original code is used (I just replaced ImuFilter::madgwickAHRSupdate with Update function from https://github.com/xioTechnologies/Open-Source-AHRS-With-x-IMU/blob/master/x-IMU%20IMU%20and%20AHRS%20Algorithms/x-IMU%20IMU%20and%20AHRS%20Algorithms/AHRS/MadgwickAHRS.cs) the output is very smooth and converges quickly (picture below).
modified_code

I suspect that a mistake was made while copying the original Madwick's code (something as silly as q1 instead of q2 could cause this).

### PR DESCRIPTION
**Pull request by mintar**
- the original implementation used 1/sqrt() instead of the fast
  invSqrt() function
- invSqrt() causes the estimate to diverge under constant input
- this commit fixes #17

### CODE REVIEW

**Comment by mintar** [comment]
I'll leave this pull request open until next week; if there are no objections, I'll merge it.

**Comment by idryanov** [comment]
No objections here. This looks like a significant bug, perhaps we should
point it out to Sebastian Madgwick?

On Wed, Nov 13, 2013 at 9:57 AM, Martin Günther notifications@github.comwrote:

> I'll leave this pull request open until next week; if there are no
> objections, I'll merge it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ccny-ros-pkg/imu_tools/pull/19#issuecomment-28400698
> .

## 

Ivan Dryanovski
The Graduate Center, City University of New York (CUNY)
CCNY Robotics Lab
http://robotics.ccny.cuny.edu/People/Dryanovski

**Comment by mintar** [comment]
Yes, maybe we should point that out. He uses the `invSqrt()` function in his C examples, but not the C# examples (that's where @tomas-c got his code snippets from).

**Comment by mintar** [comment]
Oh, and by the way: the performance penalty of not using the fast `invSqrt()` implementation here is negligible on modern PCs (I've tested that).

**Comment by tomas-c** [comment]
I looked into the inverse square root implementation.

The main problem is the line "long i = _(long_)&y;" where 64bits are read from a 32bit number. The result depends on what variable is defined after the y. In this case "i" is defined after "y" so the end result is pretty much random :) Because there is "(i >>1)" the result sometimes ends up having MSB=1 - correct magnitude but negative sign.

There are 3 ways to solve it:
    (1) Use int instead of long
    (2) Use the union method (http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Reciprocal_of_the_square_root)
    (3) Use 1/sqrt(x)

I myself prefer (2) as it the most elegant and does not use nasty conversion to integer and back.

**Comment by tomas-c** [comment]
If you haven't already contacted him, I will do that this evening.

**Comment by mintar** [comment]
@tomas-c, you were right again, the union method fixes the problem. :-)

I've added a pull request (#20) that implements that solution. If there are no objections, I'll close this request and merge #20 instead.

**Comment by mintar** [comment]
Rejected in favor of #20 .

**Pull request closed without merging**
